# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 602)
        MainWindow.setMinimumSize(QtCore.QSize(815, 602))
        MainWindow.setMaximumSize(QtCore.QSize(815, 602))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tabTraining = QtWidgets.QWidget()
        self.tabTraining.setObjectName("tabTraining")
        self.label = QtWidgets.QLabel(self.tabTraining)
        self.label.setGeometry(QtCore.QRect(50, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tabTraining)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.btnRutaDespoblacion = QtWidgets.QPushButton(self.tabTraining)
        self.btnRutaDespoblacion.setGeometry(QtCore.QRect(290, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRutaDespoblacion.setFont(font)
        self.btnRutaDespoblacion.setObjectName("btnRutaDespoblacion")
        self.btnRutaNoDespoblacion = QtWidgets.QPushButton(self.tabTraining)
        self.btnRutaNoDespoblacion.setGeometry(QtCore.QRect(290, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRutaNoDespoblacion.setFont(font)
        self.btnRutaNoDespoblacion.setObjectName("btnRutaNoDespoblacion")
        self.lblRutaDespoblacion = QtWidgets.QLabel(self.tabTraining)
        self.lblRutaDespoblacion.setGeometry(QtCore.QRect(420, 30, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblRutaDespoblacion.setFont(font)
        self.lblRutaDespoblacion.setObjectName("lblRutaDespoblacion")
        self.lblRutaNoDespoblacion = QtWidgets.QLabel(self.tabTraining)
        self.lblRutaNoDespoblacion.setGeometry(QtCore.QRect(420, 80, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblRutaNoDespoblacion.setFont(font)
        self.lblRutaNoDespoblacion.setObjectName("lblRutaNoDespoblacion")
        self.label_5 = QtWidgets.QLabel(self.tabTraining)
        self.label_5.setGeometry(QtCore.QRect(50, 130, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.cbAlgoritmo = QtWidgets.QComboBox(self.tabTraining)
        self.cbAlgoritmo.setGeometry(QtCore.QRect(290, 130, 241, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbAlgoritmo.setFont(font)
        self.cbAlgoritmo.setObjectName("cbAlgoritmo")
        self.cbAlgoritmo.addItem("")
        self.cbAlgoritmo.addItem("")
        self.cbAlgoritmo.addItem("")
        self.btnGenerarModelo = QtWidgets.QPushButton(self.tabTraining)
        self.btnGenerarModelo.setGeometry(QtCore.QRect(320, 190, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnGenerarModelo.setFont(font)
        self.btnGenerarModelo.setObjectName("btnGenerarModelo")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabTraining)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 270, 711, 241))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(170, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(350, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lblPrecision = QtWidgets.QLabel(self.groupBox_2)
        self.lblPrecision.setGeometry(QtCore.QRect(280, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblPrecision.setFont(font)
        self.lblPrecision.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPrecision.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPrecision.setObjectName("lblPrecision")
        self.lblAcierto = QtWidgets.QLabel(self.groupBox_2)
        self.lblAcierto.setGeometry(QtCore.QRect(460, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblAcierto.setFont(font)
        self.lblAcierto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblAcierto.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAcierto.setObjectName("lblAcierto")
        self.tableEstadisticas = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableEstadisticas.setGeometry(QtCore.QRect(50, 90, 591, 121))
        self.tableEstadisticas.setObjectName("tableEstadisticas")
        self.tableEstadisticas.setColumnCount(3)
        self.tableEstadisticas.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticas.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticas.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticas.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticas.setHorizontalHeaderItem(2, item)
        self.tableEstadisticas.horizontalHeader().setDefaultSectionSize(135)
        self.tabWidget.addTab(self.tabTraining, "")
        self.tabTesting = QtWidgets.QWidget()
        self.tabTesting.setObjectName("tabTesting")
        self.label_3 = QtWidgets.QLabel(self.tabTesting)
        self.label_3.setGeometry(QtCore.QRect(50, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.btnRutaModelo = QtWidgets.QPushButton(self.tabTesting)
        self.btnRutaModelo.setGeometry(QtCore.QRect(290, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRutaModelo.setFont(font)
        self.btnRutaModelo.setObjectName("btnRutaModelo")
        self.btnRutaNoticias = QtWidgets.QPushButton(self.tabTesting)
        self.btnRutaNoticias.setGeometry(QtCore.QRect(290, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRutaNoticias.setFont(font)
        self.btnRutaNoticias.setObjectName("btnRutaNoticias")
        self.label_4 = QtWidgets.QLabel(self.tabTesting)
        self.label_4.setGeometry(QtCore.QRect(50, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.lblRutaNoticias = QtWidgets.QLabel(self.tabTesting)
        self.lblRutaNoticias.setGeometry(QtCore.QRect(420, 80, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblRutaNoticias.setFont(font)
        self.lblRutaNoticias.setObjectName("lblRutaNoticias")
        self.lblRutaModelo = QtWidgets.QLabel(self.tabTesting)
        self.lblRutaModelo.setGeometry(QtCore.QRect(420, 30, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblRutaModelo.setFont(font)
        self.lblRutaModelo.setObjectName("lblRutaModelo")
        self.groupBox = QtWidgets.QGroupBox(self.tabTesting)
        self.groupBox.setGeometry(QtCore.QRect(20, 180, 761, 341))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.tabWidget.addTab(self.tabTesting, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clasificador de Noticias"))
        self.label.setText(_translate("MainWindow", "Noticias despoblación"))
        self.label_2.setText(_translate("MainWindow", "Noticias no despoblación"))
        self.btnRutaDespoblacion.setText(_translate("MainWindow", "Abrir ruta"))
        self.btnRutaNoDespoblacion.setText(_translate("MainWindow", "Abrir ruta"))
        self.lblRutaDespoblacion.setText(_translate("MainWindow", "Ruta: "))
        self.lblRutaNoDespoblacion.setText(_translate("MainWindow", "Ruta: "))
        self.label_5.setText(_translate("MainWindow", "Algoritmo"))
        self.cbAlgoritmo.setCurrentText(_translate("MainWindow", "Árbol de decisión"))
        self.cbAlgoritmo.setItemText(0, _translate("MainWindow", "Árbol de decisión"))
        self.cbAlgoritmo.setItemText(1, _translate("MainWindow", "K-nn"))
        self.cbAlgoritmo.setItemText(2, _translate("MainWindow", "Naive Bayes"))
        self.btnGenerarModelo.setText(_translate("MainWindow", "Generar Modelo"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Estadísticas"))
        self.label_6.setText(_translate("MainWindow", "Precisión"))
        self.label_7.setText(_translate("MainWindow", "Acierto"))
        self.lblPrecision.setText(_translate("MainWindow", "%"))
        self.lblAcierto.setText(_translate("MainWindow", "%"))
        item = self.tableEstadisticas.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pred. Despoblacion"))
        item = self.tableEstadisticas.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pred. No Despoblacion"))
        item = self.tableEstadisticas.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Recall"))
        item = self.tableEstadisticas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "true Despoblacion"))
        item = self.tableEstadisticas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "true No Despoblacion"))
        item = self.tableEstadisticas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Precision"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTraining), _translate("MainWindow", "Training"))
        self.label_3.setText(_translate("MainWindow", "Modelo"))
        self.btnRutaModelo.setText(_translate("MainWindow", "Abrir Modelo"))
        self.btnRutaNoticias.setText(_translate("MainWindow", "Abrir ruta"))
        self.label_4.setText(_translate("MainWindow", "Noticias"))
        self.lblRutaNoticias.setText(_translate("MainWindow", "Ruta: "))
        self.lblRutaModelo.setText(_translate("MainWindow", "Ruta: "))
        self.groupBox.setTitle(_translate("MainWindow", "Resultados"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTesting), _translate("MainWindow", "Testing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

