# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 700)
        MainWindow.setMinimumSize(QtCore.QSize(815, 700))
        MainWindow.setMaximumSize(QtCore.QSize(815, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 651))
        self.tabWidget.setObjectName("tabWidget")
        self.tabTraining = QtWidgets.QWidget()
        self.tabTraining.setObjectName("tabTraining")
        self.label = QtWidgets.QLabel(self.tabTraining)
        self.label.setGeometry(QtCore.QRect(50, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tabTraining)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.btnRutaDespoblacion = QtWidgets.QPushButton(self.tabTraining)
        self.btnRutaDespoblacion.setGeometry(QtCore.QRect(290, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRutaDespoblacion.setFont(font)
        self.btnRutaDespoblacion.setObjectName("btnRutaDespoblacion")
        self.btnRutaNoDespoblacion = QtWidgets.QPushButton(self.tabTraining)
        self.btnRutaNoDespoblacion.setGeometry(QtCore.QRect(290, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRutaNoDespoblacion.setFont(font)
        self.btnRutaNoDespoblacion.setObjectName("btnRutaNoDespoblacion")
        self.lblRutaDespoblacion = QtWidgets.QLabel(self.tabTraining)
        self.lblRutaDespoblacion.setGeometry(QtCore.QRect(420, 30, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblRutaDespoblacion.setFont(font)
        self.lblRutaDespoblacion.setObjectName("lblRutaDespoblacion")
        self.lblRutaNoDespoblacion = QtWidgets.QLabel(self.tabTraining)
        self.lblRutaNoDespoblacion.setGeometry(QtCore.QRect(420, 80, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblRutaNoDespoblacion.setFont(font)
        self.lblRutaNoDespoblacion.setObjectName("lblRutaNoDespoblacion")
        self.label_5 = QtWidgets.QLabel(self.tabTraining)
        self.label_5.setGeometry(QtCore.QRect(50, 130, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.cbAlgoritmo = QtWidgets.QComboBox(self.tabTraining)
        self.cbAlgoritmo.setGeometry(QtCore.QRect(290, 130, 241, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbAlgoritmo.setFont(font)
        self.cbAlgoritmo.setObjectName("cbAlgoritmo")
        self.cbAlgoritmo.addItem("")
        self.cbAlgoritmo.addItem("")
        self.cbAlgoritmo.addItem("")
        self.btnGenerarModelo = QtWidgets.QPushButton(self.tabTraining)
        self.btnGenerarModelo.setGeometry(QtCore.QRect(310, 190, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnGenerarModelo.setFont(font)
        self.btnGenerarModelo.setObjectName("btnGenerarModelo")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabTraining)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 250, 721, 341))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(170, 80, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(350, 80, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lblPrecision = QtWidgets.QLabel(self.groupBox_2)
        self.lblPrecision.setGeometry(QtCore.QRect(280, 80, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblPrecision.setFont(font)
        self.lblPrecision.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPrecision.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPrecision.setObjectName("lblPrecision")
        self.lblAcierto = QtWidgets.QLabel(self.groupBox_2)
        self.lblAcierto.setGeometry(QtCore.QRect(460, 80, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblAcierto.setFont(font)
        self.lblAcierto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblAcierto.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAcierto.setObjectName("lblAcierto")
        self.tableEstadisticas = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableEstadisticas.setGeometry(QtCore.QRect(80, 130, 541, 121))
        self.tableEstadisticas.setObjectName("tableEstadisticas")
        self.tableEstadisticas.setColumnCount(3)
        self.tableEstadisticas.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticas.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticas.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticas.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticas.setHorizontalHeaderItem(2, item)
        self.tableEstadisticas.horizontalHeader().setDefaultSectionSize(135)
        self.btnGuardarModelo = QtWidgets.QPushButton(self.groupBox_2)
        self.btnGuardarModelo.setGeometry(QtCore.QRect(270, 280, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnGuardarModelo.setFont(font)
        self.btnGuardarModelo.setObjectName("btnGuardarModelo")
        self.lblAlgoritmo = QtWidgets.QLabel(self.groupBox_2)
        self.lblAlgoritmo.setGeometry(QtCore.QRect(220, 30, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblAlgoritmo.setFont(font)
        self.lblAlgoritmo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblAlgoritmo.setText("")
        self.lblAlgoritmo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAlgoritmo.setObjectName("lblAlgoritmo")
        self.tabWidget.addTab(self.tabTraining, "")
        self.tabTesting = QtWidgets.QWidget()
        self.tabTesting.setObjectName("tabTesting")
        self.label_3 = QtWidgets.QLabel(self.tabTesting)
        self.label_3.setGeometry(QtCore.QRect(-90, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.btnRutaModelo = QtWidgets.QPushButton(self.tabTesting)
        self.btnRutaModelo.setGeometry(QtCore.QRect(160, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRutaModelo.setFont(font)
        self.btnRutaModelo.setObjectName("btnRutaModelo")
        self.btnRutaNoticias = QtWidgets.QPushButton(self.tabTesting)
        self.btnRutaNoticias.setGeometry(QtCore.QRect(500, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRutaNoticias.setFont(font)
        self.btnRutaNoticias.setObjectName("btnRutaNoticias")
        self.label_4 = QtWidgets.QLabel(self.tabTesting)
        self.label_4.setGeometry(QtCore.QRect(250, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.lblRutaNoticias = QtWidgets.QLabel(self.tabTesting)
        self.lblRutaNoticias.setGeometry(QtCore.QRect(400, 70, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblRutaNoticias.setFont(font)
        self.lblRutaNoticias.setObjectName("lblRutaNoticias")
        self.lblRutaModelo = QtWidgets.QLabel(self.tabTesting)
        self.lblRutaModelo.setGeometry(QtCore.QRect(60, 70, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblRutaModelo.setFont(font)
        self.lblRutaModelo.setObjectName("lblRutaModelo")
        self.groupBox = QtWidgets.QGroupBox(self.tabTesting)
        self.groupBox.setGeometry(QtCore.QRect(10, 370, 761, 241))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.tableResultados = QtWidgets.QTableWidget(self.groupBox)
        self.tableResultados.setGeometry(QtCore.QRect(10, 20, 741, 161))
        self.tableResultados.setObjectName("tableResultados")
        self.tableResultados.setColumnCount(2)
        self.tableResultados.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultados.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultados.setHorizontalHeaderItem(1, item)
        self.btnExportar = QtWidgets.QPushButton(self.groupBox)
        self.btnExportar.setGeometry(QtCore.QRect(290, 190, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnExportar.setFont(font)
        self.btnExportar.setObjectName("btnExportar")
        self.btnClasificar = QtWidgets.QPushButton(self.tabTesting)
        self.btnClasificar.setGeometry(QtCore.QRect(300, 320, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnClasificar.setFont(font)
        self.btnClasificar.setObjectName("btnClasificar")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabTesting)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 110, 711, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(290, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(490, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.lblPrecisionTesting = QtWidgets.QLabel(self.groupBox_3)
        self.lblPrecisionTesting.setGeometry(QtCore.QRect(400, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblPrecisionTesting.setFont(font)
        self.lblPrecisionTesting.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPrecisionTesting.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPrecisionTesting.setObjectName("lblPrecisionTesting")
        self.lblAciertoTesting = QtWidgets.QLabel(self.groupBox_3)
        self.lblAciertoTesting.setGeometry(QtCore.QRect(600, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblAciertoTesting.setFont(font)
        self.lblAciertoTesting.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblAciertoTesting.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAciertoTesting.setObjectName("lblAciertoTesting")
        self.lblAlgoritmoTesting = QtWidgets.QLabel(self.groupBox_3)
        self.lblAlgoritmoTesting.setGeometry(QtCore.QRect(100, 30, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblAlgoritmoTesting.setFont(font)
        self.lblAlgoritmoTesting.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblAlgoritmoTesting.setText("")
        self.lblAlgoritmoTesting.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAlgoritmoTesting.setObjectName("lblAlgoritmoTesting")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(-10, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.tableEstadisticasTesting = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableEstadisticasTesting.setGeometry(QtCore.QRect(80, 70, 541, 121))
        self.tableEstadisticasTesting.setObjectName("tableEstadisticasTesting")
        self.tableEstadisticasTesting.setColumnCount(3)
        self.tableEstadisticasTesting.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticasTesting.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticasTesting.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticasTesting.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticasTesting.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticasTesting.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadisticasTesting.setHorizontalHeaderItem(2, item)
        self.tableEstadisticasTesting.horizontalHeader().setDefaultSectionSize(135)
        self.tabWidget.addTab(self.tabTesting, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clasificador de Noticias"))
        self.label.setText(_translate("MainWindow", "Noticias despoblación"))
        self.label_2.setText(_translate("MainWindow", "Noticias no despoblación"))
        self.btnRutaDespoblacion.setText(_translate("MainWindow", "Abrir ruta"))
        self.btnRutaNoDespoblacion.setText(_translate("MainWindow", "Abrir ruta"))
        self.lblRutaDespoblacion.setText(_translate("MainWindow", "Ruta: "))
        self.lblRutaNoDespoblacion.setText(_translate("MainWindow", "Ruta: "))
        self.label_5.setText(_translate("MainWindow", "Algoritmo"))
        self.cbAlgoritmo.setCurrentText(_translate("MainWindow", "Árbol de decisión"))
        self.cbAlgoritmo.setItemText(0, _translate("MainWindow", "Árbol de decisión"))
        self.cbAlgoritmo.setItemText(1, _translate("MainWindow", "K-nn"))
        self.cbAlgoritmo.setItemText(2, _translate("MainWindow", "Naive Bayes"))
        self.btnGenerarModelo.setText(_translate("MainWindow", "Generar Modelo"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Estadísticas"))
        self.label_6.setText(_translate("MainWindow", "Precisión"))
        self.label_7.setText(_translate("MainWindow", "Acierto"))
        self.lblPrecision.setText(_translate("MainWindow", "%"))
        self.lblAcierto.setText(_translate("MainWindow", "%"))
        item = self.tableEstadisticas.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pred. Despoblacion"))
        item = self.tableEstadisticas.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pred. No Despoblacion"))
        item = self.tableEstadisticas.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Recall"))
        item = self.tableEstadisticas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "true Despoblacion"))
        item = self.tableEstadisticas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "true No Despoblacion"))
        item = self.tableEstadisticas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Precision"))
        self.btnGuardarModelo.setText(_translate("MainWindow", "Guardar Modelo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTraining), _translate("MainWindow", "Training"))
        self.label_3.setText(_translate("MainWindow", "Modelo "))
        self.btnRutaModelo.setText(_translate("MainWindow", "Abrir Modelo"))
        self.btnRutaNoticias.setText(_translate("MainWindow", "Abrir ruta"))
        self.label_4.setText(_translate("MainWindow", "Noticias"))
        self.lblRutaNoticias.setText(_translate("MainWindow", "Ruta: "))
        self.lblRutaModelo.setText(_translate("MainWindow", "Ruta: "))
        self.groupBox.setTitle(_translate("MainWindow", "Resultados"))
        item = self.tableResultados.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Noticia"))
        item = self.tableResultados.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Predicción"))
        self.btnExportar.setText(_translate("MainWindow", "Exportar"))
        self.btnClasificar.setText(_translate("MainWindow", "Clasificar Noticias"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Modelo"))
        self.label_8.setText(_translate("MainWindow", "Precisión"))
        self.label_9.setText(_translate("MainWindow", "Acierto"))
        self.lblPrecisionTesting.setText(_translate("MainWindow", "%"))
        self.lblAciertoTesting.setText(_translate("MainWindow", "%"))
        self.label_10.setText(_translate("MainWindow", "Algoritmo"))
        item = self.tableEstadisticasTesting.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pred. Despoblacion"))
        item = self.tableEstadisticasTesting.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pred. No Despoblacion"))
        item = self.tableEstadisticasTesting.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Recall"))
        item = self.tableEstadisticasTesting.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "true Despoblacion"))
        item = self.tableEstadisticasTesting.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "true No Despoblacion"))
        item = self.tableEstadisticasTesting.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Precision"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTesting), _translate("MainWindow", "Testing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

